import json


print("=== FNF Chart Offset Tool ===")
# Generated by Grok lol


# === CONFIGURE THESE ===
input_file = "bloodshed-metadata.json"   # Change if your file has a different name
output_file = "bloodshed-metadata-modified.json"
cutoff = 270690
offset = -914.285714285
# ========================


try:
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    print(f"Loaded {input_file} successfully!")
    
    modified_count = 0
    for tc in data.get('timeChanges', []):
        if isinstance(tc, dict) and 't' in tc and tc['t'] > cutoff:
            original_t = tc['t']
            tc['t'] = round(original_t + offset, 9)   # high precision
            modified_count += 1
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=1)
    
    print(f"\n✅ Success!")
    print(f"   Modified {modified_count} timeChange entries")
    print(f"   Output saved to: {output_file}")
    
except FileNotFoundError:
    print(f"❌ Error: Could not find '{input_file}'")
    print("Make sure the script is in the same folder as your JSON file.")
except json.JSONDecodeError as e:
    print("❌ Error: Invalid JSON file")
    print(e)
except Exception as e:
    print("❌ Unexpected error:", e)

print("\nPress Enter to close...")
input()
