#pragma header

// Code generated by Grok lol
// I'm sorry I felt lazy ;-;   -Haz

uniform float _alpha;
uniform float iTime;
const vec3 iResolution = vec3(1280.0, 720.0, 1.0);


void main() {
	if (_alpha <= 0.0){
		gl_FragColor = vec4(0.0);
	}else{
		vec2 fragCoord = openfl_TextureCoordv.xy * iResolution.xy;
		
		vec2 uv = fragCoord.xy / iResolution.xy;
		uv = uv * 2.0 - 1.0;  // Center coordinates: -1 to 1
		uv.x *= iResolution.x / iResolution.y;  // Correct for aspect ratio

		float r = length(uv);        	// Radius (distance from center)
		float theta = atan(uv.y, uv.x);	// Angle (-PI to PI)

		// Spiral parameters (tweak these!)
		float arms = 4.0;            	// Number of spiral arms (2 matches your image well)
		float tightness = 8.0;       	// How tight/fast the spiral winds (higher = more turns)
		float base_thickness = -0.175;   	// Minimum thickness near center (0-1 range)
		float thickness_growth = 2.75;  	// How much thicker it gets toward the edge (0-1)
		float softness = 0.00;       	// Edge softness (higher = blurrier gradients)

		float thickness = base_thickness + thickness_growth * r;
		thickness = clamp(thickness, 0.0, 0.5);
		softness *= thickness;

		// Create the spiral wave
		float spiral = theta + tightness * r;  // Basic spiral (Archimedean-like)
		spiral = sin(spiral * arms + (iTime*-5.0));           // Periodic bands for arms

		// NEW: Remap sin (-1 to 1) -> (0 to 1) repeating sawtooth for clean filling
		float wave = spiral * 0.5 + 0.5;  // Now 0 to 1 (one full period per arm)
		float band = 1.0 - smoothstep(thickness - softness, thickness + softness, wave);

		// Colors to match your brownish/gold tones
		vec3 dark = vec3(0.4196, 0.35294, 0.18039);   
		vec3 light = vec3(0.56, 0.4745, 0.243137);   

		vec3 color = mix(dark, light, band) * 0.75; // Dull it a bit to counter the bloom

		gl_FragColor = vec4(color, 1.0);
		gl_FragColor *= _alpha;
	}
}

